### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by sheri-thomson** [sheri-thomson/horizontal-nav#1]
@thomasjbradley

Hello! Ive been working on this for some time now and have stalled. I plan to review the tutorials before moving forward but wanted to see if you could review my code. How could I organize it in a more simplified way, if at all? I just want to make sure that I am relatively on track..

Thanks,
Sheri

**Comment by thomasjbradley** [comment]
The HTML & CSS code looks very well organized and good! I see that it's not working fully properly yet, but the code looks good.

**Comment by sheri-thomson** [comment]
@thomasjbradley 

Markbot won't accept my margin value and I've tried a range of numbers including the ones you suggested in the assignment. 

Markbot is also saying that my font in CSS - Line 20.. isn't the correct font-family value.

**Comment by thomasjbradley** [comment]
*Re: margin—*

You're talking about the `margin` on `<body>`? That should be `0`.

---

*Re: font family—*

You can’t just copy and paste from Google for the `font-family` declaration because their code isn’t always correct; you need to use your judgment a little. In this case Bevan isn’t a `cursive` font it’s a `serif` font family; that should be the backup.

**Comment by sheri-thomson** [comment]
@thomasjbradley 

Ok got it!

I can't get my hover element to target the whole box, it's only highlighting the text ...

Also, visually speaking I'm way off percentage wise, is there an easier way to getting it lined up accordingly?

**Comment by thomasjbradley** [comment]
*Re: hover—*

I think the problem is that in the `:hover` code the `color` is being changed, but it should be `background-color`

---

*Re: screenshots—*

I think the biggest change is that there are margins and paddings in the code that are not listed in the assignment requirements. I see lots of margins and paddings of different values—but it’s much simpler than that.

**Comment by sheri-thomson** [comment]
@thomasjbradley 

YES!  Got it! 

My kids were like "Mom is hacking codes for school" lol...

**Comment by thomasjbradley** [comment]
> "Mom is hacking codes for school" 

Love it!

---

*Re: review—*

The HTML is fantastic; with a few small changes:

1. The extra `<div>` tag is unnecessary to create the layout—and I see it isn’t even used in the CSS.
https://github.com/thom0610/horizontal-nav/blob/gh-pages/index.html#L17-L24
2. There shouldn’t be two Google Font `<link>` tags. In the Google Fonts interface click the plus for both fonts and they’ll both be added to the cart-like drawer—therefore giving you only one `<link>` tag to paste into your code.
https://github.com/thom0610/horizontal-nav/blob/gh-pages/index.html#L8-L9

The CSS looks pretty good but could be simplified in the following ways:

- Specifying `text-align` and `background-color` again in the `h1` is unnecessary because the same properties are set on `header` and will be inherited:
https://github.com/thom0610/horizontal-nav/blob/gh-pages/css/main.css#L25-L26
- Similarly, specifying `font-family` again on `nav li` isn’t necessary because it will be inherited from the `nav ul`:
https://github.com/thom0610/horizontal-nav/blob/gh-pages/css/main.css#L42
- I know this is something that wasn’t obvious but—you didn’t need `font-size` at all to complete the assignment. Usually I specify the required `font-sizes` like I did the `margin` & `padding` when they’re required.

Okay, for the full highlighting link box… it really comes down to where you put specific properties.

- The only properties actually necessary on the `nav li` are `margin-bottom` and `display: inline-block`. *Absolutely everything else should be on the `<a>` tag.*
- The `<a>` tag should be doing all the heavy lifting: `padding`, `background-color`, `border-radius`, `color`, etc. But remember because `<a>` tags are `inline` by default it would also need `display: inline-block` for the `padding` to work properly.
